[mypy]
ignore_missing_imports = True
check_untyped_defs = False
no_silence_site_packages = False

[mypy-test_all]
ignore_errors = True

[mypy-test_load]
ignore_errors = True

[mypy-test_system]
ignore_errors = True

[mypy-run_deep_audit]
ignore_errors = True
